### ISSUE TITLE
Extra arguments for meta_factory

### ISSUE THREAD

**Issue by Nemexur** [catalyst-team/hydra-slayer#24]
Hello,
Thank you for this package. It helps me a lot to keep modules initialization very readable and clean.

In my projects, I often use `from_params` `classmethod` to instantiate modules from complex `jsonnet` config. In general, it works great with hydra-slayer. However, there are some aspects:
1. Instead of `get_from_params` I use `from_params`.
2. Some of the modules require lazy initialization.

To accomplish that, I can modify `_target_` to work with `from_params` function or add custom methods to `Registry`. All in all, it works fine, but it would be great if I could conveniently tell hydra-slayer through config to work with custom `classmethod` for both `call_meta_factory` and `partial_meta_factory`.
For instance, something like that:
```
local init = {
    "meta_factory": {
        "_target_": "hydra_slayer.call_meta_factory",
        "method": "from_params",
    },
};
local lazy_init = {
    "meta_factory": {
        "_target_": "hydra_slayer.partial_meta_factory",
        "method": "from_params",
    },
};
```

**Comment by bagxi** [comment]
Hi,

1. Thanks for the proposal. I guess it can be done by adapting [this](https://github.com/catalyst-team/hydra-slayer/blob/master/hydra_slayer/functional.py#L71) `if`, but I need some time to think about how to do it in a more general way.

2. Please try to use `Registry.late_add` for lazy initialization.

**Comment by bagxi** [comment]
bwt, in the first case you also can use:
```
local init = {
    "_target_": "datasets.Dataset.get_from_params",
    "path_to_images": "data/path/to/images",
    "path_to_annotations": "data/path/to/annotations",
};
```
